# -*- coding: utf-8 -*-
"""AULA_1_(Python_+_Machine_Learning)_—_Classificação_Supervisionada.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TfyRblsa1oJhZngtBG8v1q-7e7IRe4Mx
"""

# AULA 1 (Python + Machine Learning) — Classificação Supervisionada
# Tema: IA, Machine Learning e Aprendizado Supervisionado (com exemplo simples)
#
# Objetivo da aula:
# 1) Entender o que são "dados" (X) e "classes/etiquetas" (y)
# 2) Treinar um modelo (fit) para aprender padrões
# 3) Fazer previsões (predict)
# 4) Medir se o modelo acertou (acurácia)
#
# Observação didática importante:
# - Este é um exemplo pequeno para aprender o conceito.
# - No mundo real, usamos MUITO mais dados para treinar e testar.
# ============================================================

# ============================================================
# 1) DEFININDO AS "FEATURES" (CARACTERÍSTICAS)
# ============================================================

# Aqui nós vamos criar um exemplo com aeronaves.
# Cada aeronave será descrita por 3 características (features).
# Cada característica será um número:
#   1 = "sim"
#   0 = "não"

# Feature 1: Civil?        (1 = civil, 0 = não civil)
# Feature 2: Motorização?  (1 = tem motor, 0 = não tem motor)
# Feature 3: Hélice?       (1 = tem hélice, 0 = não tem hélice)

# Importante: em Machine Learning, as features viram uma "lista" de números.
# Exemplo: [1, 0, 1] significa:
#   Civil? = 1 (sim)
#   Motorização? = 0 (não)
#   Hélice? = 1 (sim)

# ============================================================
# 2) CRIANDO OS DADOS DE TREINO (X) E AS CLASSES (y)
# ============================================================

# Vamos criar exemplos de aeronaves com "asa fixa" e "asa rotativa".
# Cada aeronave é uma lista com 3 números (as 3 features).

# Três aeronaves da classe "asa fixa" (exemplos)
fixa1 = [0, 1, 0]  # não civil, tem motor, não tem hélice
fixa2 = [0, 1, 1]  # não civil, tem motor, tem hélice
fixa3 = [1, 1, 0]  # civil, tem motor, não tem hélice

# Três aeronaves da classe "asa rotativa" (exemplos)
rotativa1 = [0, 1, 1]  # não civil, tem motor, tem hélice
rotativa2 = [1, 0, 1]  # civil, não tem motor, tem hélice
rotativa3 = [1, 1, 1]  # civil, tem motor, tem hélice

# Agora vamos juntar todas as aeronaves em uma lista chamada "dados".
# Em ML, isso é o nosso X (dados de entrada).
dados = [fixa1, fixa2, fixa3, rotativa1, rotativa2, rotativa3]

# Agora precisamos dizer qual é a classe correta de cada aeronave.
# Isso é o nosso y (classes / labels / etiquetas).
#
# Vamos definir:
#   1 = asa fixa
#   0 = asa rotativa
#
# Então, como as 3 primeiras são fixa, colocamos 1,1,1.
# E como as 3 últimas são rotativa, colocamos 0,0,0.
classes = [1, 1, 1, 0, 0, 0]

# Resumo didático:
# - "dados" (X) = características das aeronaves (listas com números)
# - "classes" (y) = resposta correta que o modelo deve aprender

# ============================================================
# 3) CRIANDO E TREINANDO O MODELO (FIT)
# ============================================================

# Vamos importar um modelo simples de classificação chamado LinearSVC.
# Ele pertence à biblioteca scikit-learn (muito usada em Machine Learning).
from sklearn.svm import LinearSVC

# Criamos o modelo.
# max_iter aumenta o número de tentativas internas para evitar avisos de convergência.
model = LinearSVC(max_iter=10000)

# Agora vem a etapa mais importante:
# fit(X, y) significa "treinar".
# Aqui o modelo tenta descobrir padrões nos dados (X) para acertar as classes (y).
model.fit(dados, classes)

# ============================================================
# 4) FAZENDO UMA PREVISÃO COM UMA AERONAVE "MISTERIOSA"
# ============================================================

# Vamos criar uma aeronave que o modelo nunca viu (um exemplo novo).
aeronave_misteriosa = [1, 1, 1]  # civil, tem motor, tem hélice

# predict recebe uma lista de exemplos (mesmo que seja 1 só).
# Por isso colocamos [aeronave_misteriosa] dentro de outra lista.
predicao = model.predict([aeronave_misteriosa])

# Vamos imprimir para entender o resultado.
# Lembrando:
#   1 = fixa
#   0 = rotativa
print("Previsão para aeronave_misteriosa:", predicao[0])

# ============================================================
# 5) TESTE COM MAIS DE UM EXEMPLO (CONJUNTO DE TESTE)
# ============================================================

# Agora vamos criar três exemplos novos para testar o modelo.
misterio1 = [1, 1, 1]
misterio2 = [1, 1, 0]
misterio3 = [0, 1, 1]

# Vamos juntar em uma lista chamada "teste".
# Em ML, isso é um X_teste.
teste = [misterio1, misterio2, misterio3]

# O modelo vai prever a classe para cada item em "teste".
previsoes = model.predict(teste)

# Vamos ver as previsões.
print("Previsões do modelo (1=fixed, 0=rotativa):", previsoes)

# ============================================================
# 6) GABARITO DO TESTE (RESPOSTAS VERDADEIRAS)
# ============================================================

# Agora precisamos do gabarito (as classes verdadeiras) desses 3 itens de teste.
# Isso é o y_teste.
#
# Aqui está o gabarito:
# misterio1 = [1,1,1] -> 0 (rotativa)
# misterio2 = [1,1,0] -> 1 (fixa)
# misterio3 = [0,1,1] -> 1 (fixa)
testes_classes = [0, 1, 1]

# Vamos imprimir para ficar claro.
print("Gabarito (classes verdadeiras):", testes_classes)

# ============================================================
# 7) CALCULANDO A TAXA DE ACERTO (ACURÁCIA) "NA MÃO"
# ============================================================

# Primeiro, vamos comparar previsão por previsão com o gabarito.
# Isso gera uma lista de True/False (verdadeiro/falso).
comparacao = (previsoes == testes_classes)

# Mostra quais foram acertos (True) e erros (False).
print("Acertou? (True=acerto, False=erro):", comparacao)

# Agora vamos contar quantos acertos tivemos.
# .sum() funciona porque True vale 1 e False vale 0.
corretos = comparacao.sum()

# O total de testes é o tamanho da lista "teste".
total = len(teste)

# Acurácia = número de acertos / total de exemplos testados
taxa_de_acerto = corretos / total

# Vamos imprimir a taxa em porcentagem.
print("Taxa de acerto (manual): %.2f%%" % (taxa_de_acerto * 100))

# ============================================================
# 8) CALCULANDO A ACURÁCIA COM FUNÇÃO PRONTA (scikit-learn)
# ============================================================

# Agora vamos usar uma função pronta para calcular a acurácia.
from sklearn.metrics import accuracy_score

# accuracy_score(y_true, y_pred) retorna a proporção de acertos.
acc_sklearn = accuracy_score(testes_classes, previsoes)

print("Taxa de acerto (sklearn): %.2f%%" % (acc_sklearn * 100))

# ============================================================
# 9) (EXTRA) MATRIZ DE CONFUSÃO — VISUALIZA OS ERROS
# ============================================================

# A matriz de confusão mostra:
# - quantos exemplos de cada classe foram previstos corretamente
# - e onde o modelo confundiu as classes
from sklearn.metrics import confusion_matrix

mat = confusion_matrix(testes_classes, previsoes)

print("\nMatriz de confusão (linhas = verdade, colunas = previsão):")
print(mat)

# Leitura didática:
# - mat[0,0]: verdade 0 e previu 0 (acerto para classe 0)
# - mat[0,1]: verdade 0 e previu 1 (erro: confundiu 0 com 1)
# - mat[1,0]: verdade 1 e previu 0 (erro: confundiu 1 com 0)
# - mat[1,1]: verdade 1 e previu 1 (acerto para classe 1)

# ============================================================
# 10) CONCLUSÃO (para falar em sala)
# ============================================================
# O que aconteceu aqui?
# - Nós demos exemplos (dados + classes)
# - O modelo aprendeu um padrão com fit()
# - O modelo fez palpites com predict()
# - Nós medimos se ele acertou (acurácia)
#
# Isso é um exemplo completo de:
# APRENDIZADO SUPERVISIONADO (Supervised Learning)
# ============================================================